### ISSUE TITLE
can't play media...

### ISSUE THREAD

**Issue by gitnoobbbb** [jellyfin/jellyfin-desktop#133]
version:1.8.0 

Playback Error
MPV Shim's player backend is not connected. This could be caused by many things. Try logging out/in again and making sure websockets work.

[prtsc](https://i.loli.net/2020/11/13/BwHLkyX1doR4zJP.png)

**Comment by iwalton3** [comment]
Are you connecting to the server through a reverse proxy? It is likely setup incorrectly so that the websocket does not work.

https://jellyfin.org/docs/general/networking/nginx.html

**Comment by alyoxia** [comment]
I'm seeing this as well after updating to 1.8.1. It was working fine before the update..

I'm not connecting via a reverse proxy.

**Comment by iwalton3** [comment]
I added that warning because it used to play in the HTML5 player if the connection was broken, which negates all the benefits of MPV Shim.

**Comment by 1024mb** [comment]
Same is happening on my end, tried with two computers, first I got the message in OP but then after log out and log in I don't get that message anymore but this time nothing happens when I click on play, nothing on the console either. Also, Jellyfin server console doesn't show any error.

**Comment by iwalton3** [comment]
Please try the new version: https://github.com/jellyfin/jellyfin-desktop/releases/tag/v1.10.0

**Comment by alyoxia** [comment]
> Please try the new version: https://github.com/jellyfin/jellyfin-desktop/releases/tag/v1.10.0

Thanks, I don't see this issue anymore when using this new release
