### ISSUE TITLE
Support Navigation buttons

### ISSUE THREAD

**Issue by gerroon** [jellyfin/jellyfin-desktop#146]
**Describe the solution you'd like**
It would be nice if the Jellyfin client navigation controls like  left and right buttons actually mapped to MPV's regular left right keyboard buttons so that the user can advance frames couple secs forward/backward.

Some of those buttons does some remoteting to Mpv like menus etc but forward and back does not work.

**Additional context**
See the image for the Jellyfin controls

https://i.imgur.com/N5LaT2B.png

**Comment by iwalton3** [comment]
This will be in the next release.
