### ISSUE TITLE
Keep the desktop app open when playing a video?

### ISSUE THREAD

**Issue by ComteNiark** [jellyfin/jellyfin-desktop#158]
Probably a dumb question with an easy answer. I just reinstalled mpv-shim due to a config mistake on my part, and now when I launch an episode, it opens up the mpv window and closes the desktop app window. Somehow that didn't happen on my previous setup, and I can't remember for the life of me how I did it, and searching the config file yielded no results.

Side note while I'm here because I don't know if this is expected behavior or not, but when watching something, I can't skip to the next episode using the mpv gui (the arrows are greyed out). This, combined with the closing window, makes it annoying when you click on the wrong episode, because now you have to un-fullscreen the mpv window, close it, wait for the desktop app to re-open... Whereas before I just had the desktop app open at all times, and if I messed up I could just alt-tab into it, select my episode, and tab back into the mpv window.

**Comment by iwalton3** [comment]
I'm pretty sure I made it hide the one window to support full-screen usage.

The arrow buttons in MPV are fundamentally incompatible with the queueing mechanism as written, but you can press < or > to skip episodes.

There is a GUI rewrite that'll be added eventually which will address both these concerns.

**Comment by ComteNiark** [comment]
> I'm pretty sure I made it hide the one window to support full-screen usage.
Ah, so that must've been some sort of bug on my previous install... Wish it didn't fix itself lol. From the wording of your post, I guess there's no way to make it behave like I asked on purpose for now?

> you can press < or > to skip episodes.
Didn't know that, but it's a good enough workaround until that GUI rewrite is done. What's the ETA on it, if you have any?

**Comment by iwalton3** [comment]
> From the wording of your post, I guess there's no way to make it behave like I asked on purpose for now?

It would require adding a config option but can be done.

**Comment by ComteNiark** [comment]
> It would require adding a config option but can be done.

Right, consider this a feature request from me then :)

**Comment by iwalton3** [comment]
I'll close this when it is implemented.

**Comment by iwalton3** [comment]
Nevermind it turns out the hiding of the window only happens if you have `display_mirroring` or `desktop_fullscreen` enabled. Because these both run in fullscreen, MPV cannot overtake them on some platforms so I hide the window.

As long as both of those are disabled it should work.
