### ISSUE TITLE
I would like the integrated browser to redirect to the base root of my server instead of Jellyfin web UI

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-desktop#165]
Hi,

This app is doing exactly what I want. Providing a way to browse my Jellyfin server easily while being able to play every video perfectly and natively.

But recently, I've upgrade my server. I am now using Organizr https://github.com/causefx/Organizr on the root of my domain. Then, organizr allow me to have all my services embedded as iFrames. I have Jellyfin, but I also have Ombi for movie requests and other stuffs.

I would like the integrated browser to redirect to the base root of my server instead of Jellyfin web UI. That way, people will be able to access my whole server instead of only Jellyfin. They will be able to go to Ombi and my other services to request movies. But I still want Jellyfin to be functionnal and MPV opening when they want to play a video.

How could I do that ? I know this is a bit unconventionnal but that would help me a lot to build my server solutions.
Thanks in advance and have a great day.

**Comment by iwalton3** [comment]
MPV Shim works by using a local server with a local copy of the web client. The web client on your server is not used.

I have long-term plans to replace the web client with something else, so it's mostly in maintenance mode for now.

**Comment by LeVraiRoiDHyrule** [comment]
I see. My final goal would be to have an app to browse my full server and that is able to play everything, as browsers can't handle HEVC or 10bit encoding. But I found no way of doing that. I'm searching how I could make a web wrapper than opens a player like MPV or whatever that is able to play everything. But I don't know where to begin.

**Comment by iwalton3** [comment]
In the long run I would suggest using a regular browser and having users select MPV Shim as their default player. I got the ability to do that merged in 10.7.0 beta.
