### ISSUE TITLE
Delay in closing mpv player

### ISSUE THREAD

**Issue by Eisa01** [jellyfin/jellyfin-desktop#175]
**Describe the bug**
When a video is open, closing mpv player has a delay. After pressing `q` or closing by `x` on top border, we have to wait a little while before the player actually closes. It is tolerable delay, but it gives a feel of lag / delay.

**Expected behavior**
mpv to close immediately or to hide after pressing `q` or closing the player.

**Desktop (please complete the following information):**
 - OS: All

**Comment by iwalton3** [comment]
This could probably be fixed by hiding the player before the stop command is sent or by running the tasks in the background.

https://github.com/jellyfin/jellyfin-desktop/blob/master/jellyfin_mpv_shim/player.py#L515

**Comment by Eisa01** [comment]
I have used similar method to fix it. I will be releasing a companion lua script that plays well with mpv shim (if that is fine). It contains multiple fixes / workarounds for most of the issues I contributed in and more. Though some are workarounds so it maybe a good solution for now or you can improve them with your knowledge.

**Comment by iwalton3** [comment]
Sounds good. I am already bundling a script for mouse support and I think that is the only way to handle the key repeat issues as the underlying keybind API in MPV doesn't support it any other way. The only think of course is making sure it doesn't impact configurability in a negative way.

**Comment by Eisa01** [comment]
Understood. I will make it user friendly with configuration options at the beginning of the script.

**Comment by iwalton3** [comment]
This specific close issue will be resolved in the next release.
