### ISSUE TITLE
Jellyfin-mpv-shim 1.9.0 fails to connect to server

### ISSUE THREAD

**Issue by fuzxi** [jellyfin/jellyfin-desktop#178]
**Describe the bug**
Running `jellyfin-mpv-shim` does not lead to the player showing up in the web UI cast menu. With `mpv_ext` set to true, an mpv instance is still launched, but cannot be cast to. The server selection/editing window that typically opens when a server is unreachable does not spawn. Everything works as expected with 1.8.1.

As a side note, 1.9.0 printed a number of lines to console which were not written to the log file, including a second traceback. I have edited those in after a double line break.

**To Reproduce**
1. Exec `jellyfin-mpv-shim`.
2. Observe the lack of jellyfin-mpv-shim players in the Jellyfin web UI.

**Expected behavior**
An external player appears in the menu.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: 1.9.0

**Error Messages**
[log-1.9.0.txt](https://github.com/jellyfin/jellyfin-desktop/files/6168395/log-1.9.0.txt)
[log-1.8.1.txt](https://github.com/jellyfin/jellyfin-desktop/files/6168397/log-1.8.1.txt)

**Comment by iwalton3** [comment]
How did you install it? It looks like the API client is outdated.

**Comment by fuzxi** [comment]
I installed jellyfin-mpv-shim and dependencies through the AUR using yay. The result is the same if I download the latest release from github and run `run.py`. If by API client you mean the package `python-jellyfin-apiclient`, my installed version is 1.7.0-1.

**Comment by iwalton3** [comment]
Did you ever install the application with pip? Maybe an old API client version from pip is being used?

**Comment by fuzxi** [comment]
Nice catch, I had 1.6.2 installed through pip. Uninstalled it and 1.9.0 works as expected. Thanks a lot for the quick help!
