### ISSUE TITLE
"player: Timeout when waiting for media duration. Stopping playback!" on H.264 and Xvid files

### ISSUE THREAD

**Issue by erperses** [jellyfin/jellyfin-desktop#181]
**Describe the bug**
Attempting to play any H.264 video file through jellyfin-mpv-shim fails. These files play properly in the official jellyfin web client, in plex-mpv-shim, and directly in mpv when mounted through sshfs.  I have also tested one Xvid file which fails in the same manner.
I have tested two HEVC files, which both appear to play properly and instantly start an mpv client when played.

**To Reproduce**
1. connect web client to jellyfin-mpv-shim
2. click play icon in web client
3. see logs in the jellyfin-mpv-shim console output

**Desktop (please complete the following information):**
- Ubuntu 20.04.2
- jellyfin 10.7.0
- jellyfin-apiclient-python 1.7.0
- jellyfin-mpv-shim 1.9.0
- Python 3.8.5
- mpv 0.32.0

**Error Messages**
[jellyfin_log.txt](https://github.com/jellyfin/jellyfin-desktop/files/6176454/jellyfin_log.txt)

**Comment by iwalton3** [comment]
Did you happen to symlink the file?

**Comment by erperses** [comment]
On my jellyfin server, yes.  The files are stored on different drives than my jellyfin media folder.

**Comment by iwalton3** [comment]
Jellyfin doesn't support playing symlinked files with direct play. Please see: https://github.com/jellyfin/jellyfin/issues/5521

**Comment by erperses** [comment]
That is unfortunate, thank you for the quick response.

**Comment by iwalton3** [comment]
There is a workaround here: https://github.com/jellyfin/jellyfin-desktop/issues/172#issuecomment-798946376

**Comment by erperses** [comment]
Thanks for the suggestion, but I just installed jellyfin to test it out.  I'll hold on switching to it until this is fixed.
I've also changed the issue title to avoid confusing people with the same issue, as https://github.com/jellyfin/jellyfin/issues/5521#issuecomment-801932479 is the reason my HEVC files would play properly.
