### ISSUE TITLE
"Playback Error" No connection to backend on 1.9.0.

### ISSUE THREAD

**Issue by ComteNiark** [jellyfin/jellyfin-desktop#183]
Getting this error: 
![image](https://user-images.githubusercontent.com/71163694/111903740-0880cc80-8a44-11eb-8a57-eebc7d4a18ee.png)

My domain is jellyfin.whitelabs.xyz, which as you can see works and has https enabled. I'm using caddy v2, which is supposed to handle websockets by itself. I can give you my caddyfile if needed.

This occasionally happened before the latest jellyfin server upgrade, but was fixed by re-logging in. Can't get it to work since then, even restarting the server and client machines does nothing.

Here is a log of me launching the app, connecting to my server and trying to read a file.
[log.txt](https://github.com/jellyfin/jellyfin-desktop/files/6177339/log.txt)

**Comment by iwalton3** [comment]
In the web app, can you see the Jellyfin MPV shim application in the cast menu? It is supposed to select it automatically but at least one other user has had it not do that.

I am assuming logging out, deleting the server, and re-adding it doesn't work.

**Comment by ComteNiark** [comment]
Just checked and yeah, selecting the shim as the casting device fixed the issue. Didn't think of doing that since I always worked flawlessly without intervention before.

Logging out and deleting the server did not fix it indeed. I even re-installed MPV shim and that didn't do it either. Let me know if there's anything I can do to help you pinpoint what causes this.

**Comment by iwalton3** [comment]
Ok so it means the auto-selection is failing, likely due to a race condition or other oddity.

**Comment by iwalton3** [comment]
The fun thing is it always worked when testing locally and it's extremely difficult to debug these webviews.

**Comment by ComteNiark** [comment]
I might just be remembering wrong, but on previous version/when it worked, there was no casting device selected on the webview. I assume it just silently casted to the mpv instance without showing a casting device on the GUI?

**Comment by iwalton3** [comment]
No it either always did that or it was broken and played inside the player.

**Comment by ComteNiark** [comment]
Might just be my faulty memory then, I never paid special attention to it, I just didn't remember the casting icon being white.

Don't hesistate if there's some sort of log I can send you or a build with extensive logging you want to share, I'd be happy to help since I have one of the offending servers.

**Comment by iwalton3** [comment]
I'm considering changing how this works in the short term to not have these connection problems.

**Comment by iwalton3** [comment]
Please try the new version: https://github.com/jellyfin/jellyfin-desktop/releases/tag/v1.10.0

**Comment by ComteNiark** [comment]
Works like a charm from my limited testing, even on first connection it launched the video with no error.
