### ISSUE TITLE
Can't see content of specific directory.

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/jellyfin-desktop#185]
**Describe the bug**
I have two directories added, A & B. In A there's directory 1, 2, 3 & 4. B is direct access to 1. At the main menu i can see A with content art on it, B has none. If i go into A i can see all content from all directories including 1, with correct cover art. If i go into B it's empty, can't see any of the content.
If i add "Folders" and through that navigate to 1, then the content shows correctly. But this is not needed for A.
Can't figure out why.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Win10
 - Version [e.g. 1.2.0] 20H2
 - Jellyfin 1.9

**Comment by iwalton3** [comment]
Does this issue exist in the web application too? I think you may have logged it against the wrong application.

**Comment by fusk-l** [comment]
I have not tried that. What exactly do you mean by "logged it against the wrong application"?

**Comment by iwalton3** [comment]
Is this problem present in the web client too or just Jellyfin Desktop (MPV Shim)?

**Comment by fusk-l** [comment]
Oh i just realized i'm talking about the server, and not the client. This is probably a server issue.

**Comment by iwalton3** [comment]
Thanks!
