### ISSUE TITLE
Version and Track selection in the WEB client does not work anymore when casting to mpv-shim

### ISSUE THREAD

**Issue by lmaonator** [jellyfin/jellyfin-desktop#191]
**Describe the bug**
I have some episodes with multiple versions, like normal and director's cut.
The default selection is the normal version and when I select the director's cut in the web client before casting, only the normal version is played.
Track selection doesn't appear to be working either, if I select different subtitle or audio tracks it always plays the default (lang_filter_audio and lang_filter_sub are both false).
This is when casting from the web client, not desktop mode, if that makes a difference.
I think this happens since Jellyfin 10.7, I didn't have this issue before with 10.6.

I can play the director's cut when the versions are not grouped so it's not a file permission problem, but selecting a different track in the web client still doesn't work. 

I enabled media decisions for the log, first play is for a grouped version with director's cut selected.
You can see the play event is for ItemId 085bdc633e5da25754eafc34d722c699 which corresponds to the Director's Cut, but it ends up playing the normal version with Id 046d98a8c04ac891acfaaba9726e8b08
The second play in the log is for a normal episode with single version, I tried selecting audio track 3 (chinese) and no subtitle track in the web ui for this, but it still ends up playing the default tracks. Can't really see anything in the log there.

**To Reproduce**
1. Select different version/tracks from default in web client
2. Cast to mpv-shim
3. Default version and tracks play

**Expected behavior**
As previously with Jellyfin 10.6 the selected version and tracks should be played.

**Desktop:**
 - OS: Ubuntu
 - Version 20.04
 - mpv-shim installed via pip

**Log**
[log.txt](https://github.com/jellyfin/jellyfin-desktop/files/6204235/log.txt)
[jellyfinlog.txt](https://github.com/jellyfin/jellyfin-desktop/files/6204237/jellyfinlog.txt)

**Comment by iwalton3** [comment]
Strange it looks like in the log the player is just getting a Play event with no Media source of or track index parameters.

**Comment by iwalton3** [comment]
Just for the sake of testing, does this happen in 1.10.1 with the desktop mode?

**Comment by lmaonator** [comment]
Just tried it, the version selection works in desktop mode, it correctly plays the director's cut.
There now is a KeyError when it tries to select the audio track though, so track selection still doesn't work, hm.
[log.txt](https://github.com/jellyfin/jellyfin-desktop/files/6204545/log.txt)

**Comment by iwalton3** [comment]
Alright there are two things here. One of which is a critical issue and will need a hotfix tonight. And the other is probably an issue with the Jellyfin server.
 - The Jellyfin server is not sending the selected track index values and media selections to the shim over the cast protocol.
 - **The web client is sending the selected audio streams as strings through the direct communication channel, which crashes media stream selection.**

**Comment by iwalton3** [comment]
> The web client is sending the selected audio streams as strings through the direct communication channel, which crashes media stream selection.

This will be fixed in the next release.

**Comment by iwalton3** [comment]
> The Jellyfin server is not sending the selected track index values and media selections to the shim over the cast protocol.

So it looks like, at least on 10.7.1, that this data is sent. However, you have to click the small play button on the page and not the larger play button on the thumbnail. Please report this issue to jellyfin/jellyfin-web.

**Comment by lmaonator** [comment]
I investigated it further and it seems like I must have confused something, I don't think track selection ever worked when casting.
The web client sends the data but the API endpoint Sessions/{sessionId}/Playing doesn't pass them on in the PlayRequest. I'll try making a PR for the server.

Thanks for the quick fixes.

**Comment by iwalton3** [comment]
It works, but only from the specific play page when you click the small play button in the bar of actions.

It's why I have that mass subtitle/audio switching feature.
