### ISSUE TITLE
shim unable to connect to server with trailing /

### ISSUE THREAD

**Issue by mia-cx** [jellyfin/jellyfin-desktop#193]
**Describe the bug**
when configuring servers, and you add in a trailing / after the domain, it fails with a connection error.
leaving out the protocol also fails the connection, i think it doesn't respect the redirect?

**To Reproduce**
- Open the "Configure Servers" menu
- add a server with a trailing / in the server address, or leaving out the correct protocol
- click connect

**Expected behavior**
i would like to be able to configure servers without having to type out `https://`, and not having to worry about trailing `/` at the end of the server address.
perhaps for the protocol, the backend could try both when none is present, or respect the redirect.

**Screenshots**
![image](https://user-images.githubusercontent.com/42698687/112476791-91fd0b00-8d72-11eb-920e-1513c29d94e7.png)

**Desktop (please complete the following information):**
 - OS: Windows, Linux, macOS
 - Version: 1.10.1

**Comment by iwalton3** [comment]
>  perhaps for the protocol, the backend could try both when none is present, or respect the redirect.

I default to port 8096 if you do not specify HTTP because a lot of users run servers on the default port.

The fix for trailing slashes in the URL will be in the next release.
