### ISSUE TITLE
Correct audio language does not play correctly on the first run.

### ISSUE THREAD

**Issue by fusk-l** [jellyfin/jellyfin-desktop#203]
**Describe the bug**
When selecting a video and choosing the desired audio language, the default is played and you have to close and restart the video before the correct audio is played. This happens every time, but only on the first run. Afterwards it works on all videos.
Setting preferred default audio language and deselecting "play default regardless" does not work. It still plays the default on the first run.

**System (please complete the following information):**
 - OS: win10
 - Jellyfin 1.10.3

**To Reproduce**
Select video.
Select audio language.
Play video.
Default audio play instead of choosen audio.
Close player and restart video.
Now correct audio language plays.

**Comment by iwalton3** [comment]
This is a bug in jellyfin-web. I am working on a fix.

**Comment by iwalton3** [comment]
Nevermind the issue is actually in the Jellyfin media server. When the server makes the PlaybackInfo call for web, it is passed the desired audio track index. The default index specified in the resulting MediaSource is then invalid and corresponds with the last set value instead.

**Comment by fusk-l** [comment]
Ah ok. Thanks for clarifying.

**Comment by iwalton3** [comment]
You can select the subtitles through the MPV menu by pressing c in the mean time.

**Comment by iwalton3** [comment]
Fixed and tested in https://github.com/jellyfin/jellyfin/pull/5750, should be eligible for back-porting.

**Comment by fusk-l** [comment]
Nice. Thanks for the assist.

**Comment by iwalton3** [comment]
https://github.com/jellyfin/jellyfin/releases/tag/v10.7.2
